COCO_TRAIN_ANN="/data/sds_sliced/coco/annotations/instances_train-50percent_bg.json"
COCO_TRAIN_IMG="/data/sds_sliced/coco/train"
COCO_VAL_ANN="/data/sds_sliced/coco/annotations/instances_val.json"
COCO_VAL_IMG="/data/sds_sliced/coco/val"
YOLO_DIR="/data/sds_sliced/yolo"
CONVERSION_INFO_FILE="/data/sds_sliced/yolo_conversion_info.json"