COCO_TRAIN_ANN="/data/sw/coco/annotations/instances_train.json"
COCO_TRAIN_IMG="/data/sw/coco/train"
COCO_VAL_ANN="/data/sw/coco/annotations/instances_val.json"
COCO_VAL_IMG="/data/sw/coco/val"
YOLO_DIR="/data/sw/yolo"
CONVERSION_INFO_FILE="/data/sw/yolo_conversion_info.json"