FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN apt update
RUN apt install git htop nano -y 
RUN apt install wget -y 
RUN apt install python3 python3-pip -y

RUN pip install tensorflow==2.14.0

RUN git clone --depth 1 --recurse-submodules https://github.com/rohansaw/automl.git
RUN pip install pycocotools --no-cache-dir

WORKDIR /automl/efficientdet
RUN pip install -r requirements.txt
RUN pip install lxml --no-cache-dir
RUN wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco/efficientdet-lite0.tgz
RUN tar xf efficientdet-lite0.tgz
RUN pip install numpy==1.23.5
ADD configs /configs
ADD train_all.sh /automl/efficientdet/train_all.sh
ADD train_all.sh /automl/efficientdet/eval.sh
ADD quantize.sh /automl/efficientdet/quantize.sh
ADD coco_to_tfrecord.sh /automl/efficientdet/coco_to_tfrecord.sh
RUN chmod +x /automl/efficientdet/train_all.sh
RUN chmod +x /automl/efficientdet/eval.sh
RUN chmod +x /automl/efficientdet/quantize.sh
RUN chmod +x /automl/efficientdet/coco_to_tfrecord.sh
RUN git clone --depth 1 --recurse-submodules https://github.com/rohansaw/automl.git

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install tqdm sahi torch